# Generated by Django 2.2.7 on 2021-06-10 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210610_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='claps',
            field=models.IntegerField(default=0),
        ),
    ]
