# Generated by Django 3.2.4 on 2021-08-23 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210612_1907'),
        ('main', '0005_auto_20210702_0602'),
    ]

    operations = [
    ]
